create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  request_id text unique not null,
  full_name text not null,
  phone text not null,
  attending text not null check (attending in ('yes', 'no')),
  guests text check (guests in ('1', '2', '3', '4', '5', '6+')),
  meal text check (meal in ('vegetarian', 'non-vegetarian')),
  created_at timestamptz not null default now()
);

alter table public.reservations enable row level security;

create policy "Guests can submit reservations"
on public.reservations
for insert
to anon
with check (
  char_length(full_name) between 2 and 120
  and phone ~ '^[+0-9 ()-]{7,30}$'
  and attending in ('yes', 'no')
  and (
    attending = 'no'
    or (
      guests in ('1', '2', '3', '4', '5', '6+')
      and meal in ('vegetarian', 'non-vegetarian')
    )
  )
);

